version: '3.1'

services:
  mysql:
    container_name: vnm-agent-service-db
    restart: always
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example # TODO: Change this
      MYSQL_NATIVE_PASSWORD: ON
      MYSQL_DATABASE: vnm-agent-db
      MYSQL_USER: 'user'
      MYSQL_PASS: 'pass'
    volumes:
      - mysql_datavolume:/var/lib/mysql

  app:
      container_name: vnm-agent-service-app
      build: .
      ports:
        - "8080:80"
      environment:
        MYSQL_HOST: mysql  # Using the service name of MySQL container
        MYSQL_PORT: 3306
        MYSQL_USER: user
        MYSQL_PASSWORD: pass
        MYSQL_DATABASE: vnm-agent-db
      depends_on:
        - mysql

volumes:
  mysql_datavolume: