# Use root/example as user/password credentials
version: '3.1'

services:
  mysql:
    container_name: vnm-agent-service-db
    restart: always
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example # TODO: Change this
      MYSQL_NATIVE_PASSWORD: ON
      MYSQL_DATABASE: vnm-agent-db
      MYSQL_USER: 'user'
      MYSQL_PASS: 'pass'
    volumes:
      - datavolume:/var/lib/mysql
volumes:
  datavolume: